#!/bin/bash
echo "🚀 Vercel 배포 가이드"
echo "==================="
echo ""
echo "1. Vercel 계정 생성:"
echo "   https://vercel.com"
echo ""
echo "2. Vercel CLI 설치:"
echo "   npm i -g vercel"
echo ""
echo "3. 로그인:"
echo "   vercel login"
echo ""
echo "4. 프로젝트 배포:"
echo "   cd /home/user/webapp"
echo "   vercel"
echo ""
echo "5. 환경변수 설정:"
echo "   vercel env add OPENAI_API_KEY"
echo "   vercel env add USE_CHATGPT"
echo ""
echo "6. 도메인 설정:"
echo "   your-family-inventory.vercel.app"
echo ""
echo "✅ 완료 후 가족들에게 공유!"
echo "   https://your-family-inventory.vercel.app"