[build]
  publish = "."
  ignore = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "https://inventory-backend-8r4j.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"