[build]
  publish = "."
  command = "echo 'Static site deployment'"

[[redirects]]
  from = "/api/*"
  to = "https://3001-i72krmbsmpnff1c7v14w6-6532622b.e2b.dev/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"