#!/bin/bash
echo "🤖 ChatGPT API 키 설정 가이드"
echo "================================"
echo ""
echo "1. OpenAI에서 API 키 발급:"
echo "   https://platform.openai.com"
echo ""
echo "2. .env 파일 수정:"
echo "   OPENAI_API_KEY=sk-proj-여기에실제키입력"
echo ""
echo "3. 서버 재시작:"
echo "   pm2 restart smart-inventory --update-env"
echo ""
echo "4. ChatGPT 활성화 확인:"
echo "   curl -X POST 'http://localhost:3001/api/chatbot' \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"message\": \"ChatGPT 테스트\"}'"
echo ""
echo "현재 설정:"
echo "OPENAI_API_KEY=$(grep OPENAI_API_KEY .env | cut -d'=' -f2)"
echo "USE_CHATGPT=$(grep USE_CHATGPT .env | cut -d'=' -f2)"
echo "CHATGPT_MODEL=$(grep CHATGPT_MODEL .env | cut -d'=' -f2)"
